import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  id: {
    nav: {
      dashboard: 'Dashboard',
      statement: 'Laporan Keuangan',
      assets: 'Pengelolaan Aset',
      settings: 'Pengaturan',
    },
    greeting: {
      morning: 'Selamat Pagi',
      afternoon: 'Selamat Siang',
      evening: 'Selamat Sore',
      night: 'Selamat Malam',
    },
    dashboard: 'Dashboard',
    history: 'Riwayat Transaksi',
    assets: 'Aset & Utang',
    accounts: 'Akun Sumber Dana',
    profile: 'Profil',
    settings: 'Pengaturan',
    lang_pref: 'Preferensi Bahasa',
    lang_id: 'Bahasa Indonesia',
    lang_en: 'English',
    firebase_conn: 'Koneksi Firebase',
    offline_mode: 'Mode Offline',
    sign_out: 'Keluar',
    add_tx: 'Tambah Transaksi',
    app_desc: 'Your Financial Integrity, Simplified.',
    settings_desc: 'Atur preferensi aplikasi dan konfigurasi Firebase.',
    main_menu: 'Menu Utama',
    recent_tx: 'Transaksi Terakhir bulan ini',
    no_recent_tx: 'Belum ada transaksi.',
    tx_count: 'Transaksi',
    tx_all: 'Semua',
    tx_income: 'Pemasukan',
    tx_expense: 'Pengeluaran',
    tx_transfer: 'Transfer',
    tx_asset: 'Aset',
    tx_debt: 'Utang',
    no_tx_period: 'Belum ada transaksi di periode ini.',
    date: 'Tanggal',
    category: 'Kategori',
    desc: 'Keterangan',
    account: 'Akun',
    amount: 'Nominal',
    action: 'Aksi',
    debt_settlement: 'Pelunasan Utang',
    asset_settlement: 'Pelunasan Piutang',
    receivables: 'Piutang',
    registered_accounts: 'Akun Terdaftar',
    add_account: 'Tambah Akun',
    real_balance: 'Saldo Riil Saat Ini',
    adjust: 'Sesuaikan',
    delete: 'Hapus',
    cancel: 'Batal',
    save: 'Simpan',
    edit: 'Edit',
    total_income: 'Total Pendapatan',
    total_expense: 'Total Pengeluaran',
    net_worth: 'Total Kekayaan Bersih',
    stats: 'Statistik',
    total_tx: 'Total Transaksi',
    account_count: 'Jumlah Akun',
    active_months: 'Bulan Aktif',
    smart_input: 'Form input cerdas dengan tipe multi-transaksi',
    type: 'Jenis',
    source: 'Sumber',
    asset_src: 'Sumber Aset',
    debt_src: 'Sumber Utang',
    receivable_src: 'Sumber Piutang',
    exist_receivable: 'Piutang Sudah Ada Sebelumnya',
    exist_debt: 'Utang Sudah Ada Sebelumnya',
    exist_asset: 'Aset Sudah Dimiliki Sebelumnya',
    exist_receivable_desc: 'Pinjaman ini diberikan sebelum menggunakan SteFin.',
    exist_debt_desc: 'Utang ini sudah ada sebelum menggunakan SteFin.',
    exist_asset_desc: 'Aset ini sudah ada sebelum menggunakan SteFin.',
    balance_unchanged: 'Saldo akun tidak berubah.',
    new_receivable: 'Piutang Diberikan dari Dana Akun',
    new_debt: 'Pinjaman Baru (Dana Masuk ke Akun)',
    new_asset: 'Aset Dibeli dengan Dana Akun',
    new_receivable_desc: 'Pinjaman ini diberikan menggunakan saldo yang tercatat. Saldo akun berkurang sebesar nominal.',
    new_debt_desc: 'Dana pinjaman diterima ke akun. Saldo akun bertambah sebesar nominal.',
    new_asset_desc: 'Aset ini dibeli menggunakan saldo yang tercatat. Saldo akun berkurang sebesar nominal.',
    level_type: 'Tipe',
    sub_category: 'Sub-Kategori',
    src_account: 'Akun Sumber',
    target_account: 'Akun Tujuan',
    select_target: 'Pilih Akun Tujuan...',
    amount_rp: 'Nominal (Rp)',
    optional_note: 'Keterangan (opsional)',
    add: 'Tambah',
    tx_edit_title: 'Edit Transaksi',
    tx_add_title: 'Tambah Transaksi',
    acc_edit_title: 'Edit Akun',
    acc_add_title: 'Tambah Akun',
    acc_name: 'Nama Akun',
    init_balance: 'Saldo Awal',
    save_acc: 'Simpan Akun',
    add_acc: 'Tambah Akun',
    edit_acc: 'Edit Akun',
    adjust_balance: 'Sesuaikan Saldo',
    adjust_desc: 'Fungsi ini akan membuat transaksi "penyesuaian" agar saldo riil di sistem sesuai dengan kenyataan.',
    actual_balance: 'Saldo Aktual di Dunia Nyata',
    diff: 'Selisih',
    adjust_btn: 'Sesuaikan Sekarang',
    account_not_changed: 'Saldo {name} tetap tidak berubah.',
    account_increased: 'Saldo {name} bertambah {amount}.',
    account_decreased: 'Saldo {name} berkurang {amount}.',
    acc_name_placeholder: 'Nama Akun (e.g. BCA, Dana)',
    acc_type_bank: 'Bank',
    acc_type_cash: 'Kas',
    acc_type_ewallet: 'E-Wallet',
    sync_desc: 'Akan disinkronkan ke Firestore',
    onboard_welcome: 'Selamat Datang di SteFin',
    onboard_welcome_desc: 'Aplikasi pencatatan keuangan pintar tanpa form ribet. Mari siapkan akun pertamamu.',
    onboard_first_acc: 'Akun Pertamamu',
    onboard_smart_form: 'Coba Form Cerdas',
    onboard_start: 'Mulai SteFin',
    add_first_acc: 'Tambah Akun Pertama',
    step_of: 'Langkah {step} dari {total}',
    basic_profile: 'Profil Dasar',
    fullname: 'Nama Lengkap',
    continue_btn: 'Lanjutkan →',
    register_accs: 'Daftarkan Akun & Saldo Awal',
    register_accs_desc: 'Semua perubahan saldo akan dihitung otomatis dari titik ini.',
    back_btn: '← Kembali',
    start_btn: 'Mulai SteFin 🚀',
    main_features: 'Fitur Utama',
    f1_desc: 'Pantau pemasukan & pengeluaran bulanan secara visual real-time.',
    f2_desc: 'Saldo nyata yang berjalan dari bulan ke bulan, bukan per-periode.',
    f3_desc: 'Peringatan cerdas jika pola keuangan menurun.',
    f4_desc: 'Data tersimpan di cloud — aman, cepat, dan bisa diakses dari mana saja.',
    welcome_name: 'Halo',
    login: 'Masuk',
    register: 'Daftar',
    min_password: 'Password (min. 6 karakter)',
    create_account: 'Buat Akun',
    or: 'atau',
    operational_report: 'Laporan Operasional',
    savings: 'Tabungan',
    from_income: 'dari pemasukan',
    cashflow: 'Arus Kas',
    cashflow_desc: 'Semua transaksi yang mengubah saldo akun bulan ini',
    debit: 'Debit (Masuk)',
    credit: 'Kredit (Keluar)',
    debt_in_req: 'Pinjaman Diterima',
    asset_bought: 'Pembelian Aset',
    receivable_given: 'Piutang Diberikan',
    total_debit: 'Total Debit',
    total_credit: 'Total Kredit',
    balance_change: 'Perubahan Saldo Akun',
    debit_minus_credit: 'Debit − Kredit',
    cashflow_6m: 'Arus Kas 6 Bulan',
    live_sync: 'Sinkronisasi Langsung',
    cash_balance: 'Saldo kas',
    loading_stefin: 'Memuat SteFin...',
    loading_data: 'Memuat data keuangan...',
    settings_verified: 'Terverifikasi',
    settings_account: 'Pengaturan Akun',
    settings_profile: 'Profil Pribadi',
    settings_profile_sub: 'Ubah nama tampilan Anda',
    settings_security: 'Keamanan',
    settings_security_sub: 'Kata sandi, PIN & Biometrik',
    settings_data: 'Kelola Data',
    settings_source: 'Kelola Sumber Dana',
    settings_source_sub: 'Atur rekening bank, e-wallet & kas',
    settings_category: 'Kelola Kategori',
    settings_category_sub: 'Lihat daftar kategori transaksi',
    settings_personalization: 'Personalisasi Tampilan',
    settings_appearance: 'Mode Tampilan',
    settings_dark_mode: 'Mode Gelap',
    settings_light_mode: 'Mode Terang',
    settings_system_mode: 'Sistem',
    display_name: 'Nama Tampilan',
    email_address: 'Alamat Email',
    edit_profile: 'Simpan Profil',
    security_pin: 'PIN Keamanan',
    enable_pin: 'Aktifkan PIN',
    disable_pin: 'Matikan PIN',
    save_pin: 'Simpan PIN',
    pin_draft: 'Buat PIN 6 digit',
    pin_confirm: 'Konfirmasi PIN',
    add_cat: 'Tambah Kategori',
    cat_type: 'Tipe Transaksi',
    cat_name: 'Nama Kategori',
    report_issue: 'Laporkan Masalah',
    settings_currency: 'Penyesuaian Mata Uang',
    settings_help: 'Informasi & Bantuan',
    settings_privacy: 'Kebijakan & Privasi',
    settings_privacy_sub: 'Syarat penggunaan & perlindungan data',
    settings_support: 'Dukungan & Bantuan',
    settings_support_sub: 'FAQ & panduan penggunaan',
    settings_feedback: 'Kirim Masukan (Feedback)',
    settings_feedback_sub: 'Bantu kami menjadi lebih baik',
    settings_signout_sub: 'Akhiri sesi dari perangkat ini',
    net_worth_label: 'Nilai Kekayaan',
    remaining_balance: 'Sisa Saldo Rekening',
    savings_label: 'Tabungan',
    cash_analysis: 'Analisis Kas',
    avg_per_day: 'Rata-rata /Hari',
    total_saving_asset: 'Total Saving (Aset)',
    credit_label: 'Kredit',
    debt_label: 'Utang',
    receivable_label: 'Piutang',
    funding_source: 'Sumber Dana',
    no_accounts: 'Belum ada akun',
    cashflow_trend: 'Arus Kas & Tren 6 Bulan',
    cashflow_summary: 'Ringkasan Cashflow',
    no_income: 'Belum ada pemasukan',
    no_expense: 'Belum ada pengeluaran',
    financial_allocation: 'Alokasi Keuangan',
    financial_allocation_sub: 'Distribusi pemasukan dan pengeluaran',
    dashboard_tx_history: 'Riwayat Transaksi',
    dashboard_tx_history_sub: '10 transaksi terakhir',
    no_transactions: 'Belum ada transaksi',
    record_income: 'Catat pemasukan',
    record_expense: 'Catat pengeluaran',
    my_assets: 'Aset Saya',
    tx_all: 'Semua',
    my_assets_sub: 'Lihat daftar dan nilai aset Anda',
    total_assets: 'Total Aset',
    asset_price_buy: 'Harga Beli',
    asset_price_now: 'Harga Skrg',
    add_asset: 'Tambah Aset',
    edit_asset: 'Edit Aset',
    delete_asset: 'Hapus Aset',
    period_weekly: 'Mingguan',
    period_monthly: 'Bulanan',
    period_yearly: 'Tahunan',
    period_custom: 'Kustom',
    email: 'Email',
    password: 'Kata Sandi',
    forgot_password: 'Lupa kata sandi?',
    reset_password_sent: 'Email peresetan kata sandi telah dikirim. Periksa kotak masuk!',
    login_with_google: 'Lanjutkan dengan Google',
    select_account_name: '— Pilih nama akun —',
    other_account_name: 'Nama akun...',
    start_journey: 'Mulai Perjalanan Finansialmu',
    onboard_tips: 'SteFin akan mencatat secara persis seluruh uang yang Anda miliki saat ini, lalu menghitung perjalanan keuanganmu ke depannya secara otomatis.',
    toast_name_empty: 'Nama tidak boleh kosong',
    toast_profile_saved: 'Profil berhasil diperbarui.',
    toast_profile_failed: 'Gagal menyimpan profil.',
    toast_email_not_found: 'Tidak dapat menemukan email.',
    toast_reset_sent: 'Email reset password berhasil dikirim.',
    toast_reset_failed: 'Gagal mengirim email reset password.',
    toast_cat_exist: 'Kategori sudah ada.',
    toast_cat_added: 'Kategori kustom ditambahkan.',
    toast_cat_failed_save: 'Gagal menyimpan kategori.',
    toast_cat_deleted: 'Kategori dihapus.',
    toast_cat_failed_delete: 'Gagal menghapus kategori.',
    toast_pin_6_digit: 'PIN harus 6 digit.',
    toast_pin_mismatch: 'Konfirmasi PIN tidak cocok.',
    toast_pin_enabled: 'PIN berhasil diaktifkan.',
    toast_pin_disabled: 'PIN dinonaktifkan.',
    toast_pin_failed: 'Gagal menyimpan PIN.',
    toast_onboarding_done: 'Onboarding selesai. Selamat datang di SteFin! 🎉',
    toast_tx_added: 'Transaksi berhasil ditambahkan.',
    toast_tx_updated: 'Transaksi diperbarui.',
    toast_tx_deleted: 'Transaksi dihapus.',
    toast_acc_added: 'Akun sumber dana ditambahkan.',
    toast_acc_updated: 'Akun diperbarui.',
    toast_acc_deleted: 'Akun dihapus.',
    toast_report_prep: 'Sedang menyiapkan laporan...',
    toast_report_sent: 'Laporan telah dikirim ke email Anda! 📧',
    toast_report_failed: 'Gagal mengirim laporan. Pastikan koneksi aman.',
    toast_receivable_paid: 'Piutang ditandai lunas.',
  },
  en: {
    nav: {
      dashboard: 'Dashboard',
      statement: 'Financial Statement',
      assets: 'Asset Management',
      settings: 'Settings',
    },
    greeting: {
      morning: 'Good Morning',
      afternoon: 'Good Afternoon',
      evening: 'Good Evening',
      night: 'Good Night',
    },
    dashboard: 'Dashboard',
    history: 'Transaction History',
    assets: 'Assets & Debts',
    accounts: 'Funding Accounts',
    profile: 'Profile',
    settings: 'Settings',
    lang_pref: 'Language Preference',
    lang_id: 'Bahasa Indonesia',
    lang_en: 'English',
    firebase_conn: 'Firebase Connection',
    offline_mode: 'Offline Mode',
    sign_out: 'Sign Out',
    add_tx: 'Add Transaction',
    app_desc: 'Your Financial Integrity, Simplified.',
    settings_desc: 'Manage application preferences and Firebase configuration.',
    main_menu: 'Main Menu',
    recent_tx: 'Recent Transactions this month',
    no_recent_tx: 'No recent transactions.',
    tx_count: 'Transactions',
    tx_all: 'All',
    tx_income: 'Income',
    tx_expense: 'Expense',
    tx_transfer: 'Transfer',
    tx_asset: 'Asset',
    tx_debt: 'Debt',
    no_tx_period: 'No transactions in this period.',
    date: 'Date',
    category: 'Category',
    desc: 'Description',
    account: 'Account',
    amount: 'Amount',
    action: 'Action',
    debt_settlement: 'Debt Settlement',
    asset_settlement: 'Receivable Settlement',
    receivables: 'Receivables',
    registered_accounts: 'Registered Accounts',
    add_account: 'Add Account',
    real_balance: 'Current Real Balance',
    adjust: 'Adjust',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    total_income: 'Total Income',
    total_expense: 'Total Expense',
    net_worth: 'Total Net Worth',
    stats: 'Statistics',
    total_tx: 'Total Transactions',
    account_count: 'Account Count',
    active_months: 'Active Months',
    smart_input: 'Smart input form with multi-transaction types',
    type: 'Type',
    source: 'Source',
    asset_src: 'Asset Source',
    debt_src: 'Debt Source',
    receivable_src: 'Receivable Source',
    exist_receivable: 'Pre-existing Receivable',
    exist_debt: 'Pre-existing Debt',
    exist_asset: 'Pre-existing Asset',
    exist_receivable_desc: 'This loan was given before using SteFin.',
    exist_debt_desc: 'This debt existed before using SteFin.',
    exist_asset_desc: 'This asset was owned before using SteFin.',
    balance_unchanged: 'Account balance remains unchanged.',
    new_receivable: 'Receivable from Account Funds',
    new_debt: 'New Debt (Funds received into Account)',
    new_asset: 'Asset Bought with Account Funds',
    new_receivable_desc: 'This loan decreases the account balance by the nominal amount.',
    new_debt_desc: 'This debt increases the account balance by the nominal amount.',
    new_asset_desc: 'This asset decreases the account balance by the nominal amount.',
    level_type: 'Level Type',
    sub_category: 'Sub-Category',
    src_account: 'Source Account',
    target_account: 'Target Account',
    select_target: 'Select Target Account...',
    amount_rp: 'Amount (Rp)',
    optional_note: 'Note (optional)',
    add: 'Add',
    tx_edit_title: 'Edit Transaction',
    tx_add_title: 'Add Transaction',
    acc_edit_title: 'Edit Account',
    acc_add_title: 'Add Account',
    acc_name: 'Account Name',
    init_balance: 'Initial Balance',
    save_acc: 'Save Account',
    add_acc: 'Add Account',
    edit_acc: 'Edit Account',
    adjust_balance: 'Adjust Balance',
    adjust_desc: 'This function creates an "adjustment" transaction so the system balance matches reality.',
    actual_balance: 'Actual Real-World Balance',
    diff: 'Difference',
    adjust_btn: 'Adjust Now',
    account_not_changed: 'Account {name} balance remains unchanged.',
    account_increased: 'Account {name} balance increased by {amount}.',
    account_decreased: 'Account {name} balance decreased by {amount}.',
    acc_name_placeholder: 'Account Name (e.g. Bank, Cash)',
    acc_type_bank: 'Bank',
    acc_type_cash: 'Cash',
    acc_type_ewallet: 'E-Wallet',
    sync_desc: 'Will be synchronized to Firestore',
    onboard_welcome: 'Welcome to SteFin',
    onboard_welcome_desc: 'Smart financial tracking without complex forms. Let\'s set up your first account.',
    onboard_first_acc: 'Your First Account',
    onboard_smart_form: 'Try Smart Form',
    onboard_start: 'Start SteFin',
    add_first_acc: 'Add First Account',
    step_of: 'Step {step} of {total}',
    basic_profile: 'Basic Profile',
    fullname: 'Full Name',
    continue_btn: 'Continue →',
    register_accs: 'Register Accounts & Initial Balance',
    register_accs_desc: 'All balance changes will be automatically calculated from this point forward.',
    back_btn: '← Back',
    start_btn: 'Start SteFin 🚀',
    main_features: 'Key Features',
    f1_desc: 'Monitor monthly income & expenses visually in real-time.',
    f2_desc: 'Real running balance month-to-month, not just isolated periods.',
    f3_desc: 'Smart warnings if financial patterns decline over 3 months.',
    f4_desc: 'Data stored securely in the cloud — fast and accessible anywhere.',
    welcome_name: 'Hello',
    login: 'Login',
    register: 'Register',
    min_password: 'Password (min. 6 characters)',
    create_account: 'Create Account',
    or: 'or',
    operational_report: 'Operational Report',
    savings: 'Savings',
    from_income: 'from income',
    cashflow: 'Cash Flow',
    cashflow_desc: 'All transactions modifying account balance this month',
    debit: 'Debit (In)',
    credit: 'Credit (Out)',
    debt_in_req: 'Debt Received',
    asset_bought: 'Asset Purchased',
    receivable_given: 'Receivable Given',
    total_debit: 'Total Debit',
    total_credit: 'Total Credit',
    balance_change: 'Balance Change',
    debit_minus_credit: 'Debit − Credit',
    cashflow_6m: '6 Months Cash Flow',
    live_sync: 'Live Sync',
    cash_balance: 'Cash balance',
    loading_stefin: 'Loading SteFin...',
    loading_data: 'Loading financial data...',
    settings_verified: 'Verified',
    settings_account: 'Account Settings',
    settings_profile: 'Personal Profile',
    settings_profile_sub: 'Change your display name',
    settings_security: 'Security',
    settings_security_sub: 'Password, PIN & Biometrics',
    settings_data: 'Data Management',
    settings_source: 'Manage Funding Sources',
    settings_source_sub: 'Set up bank accounts, e-wallets, and cash',
    settings_category: 'Manage Categories',
    settings_category_sub: 'View transaction category list',
    settings_personalization: 'Personalization',
    settings_appearance: 'Appearance Mode',
    settings_dark_mode: 'Dark Mode',
    settings_light_mode: 'Light Mode',
    settings_system_mode: 'System',
    display_name: 'Display Name',
    email_address: 'Email Address',
    edit_profile: 'Save Profile',
    security_pin: 'Security PIN',
    enable_pin: 'Enable PIN',
    disable_pin: 'Disable PIN',
    save_pin: 'Save PIN',
    pin_draft: 'Enter 6-digit PIN',
    pin_confirm: 'Confirm PIN',
    add_cat: 'Add Category',
    cat_type: 'Transaction Type',
    cat_name: 'Category Name',
    report_issue: 'Report Issue',
    settings_currency: 'Currency Settings',
    settings_help: 'Information & Help',
    settings_privacy: 'Privacy & Policy',
    settings_privacy_sub: 'Terms of use & data protection',
    settings_support: 'Support & Help',
    settings_support_sub: 'FAQs & usage guides',
    settings_feedback: 'Send Feedback',
    settings_feedback_sub: 'Help us improve',
    settings_signout_sub: 'End session on this device',
    net_worth_label: 'Net Worth',
    remaining_balance: 'Remaining Account Balance',
    savings_label: 'Savings',
    cash_analysis: 'Cash Analysis',
    avg_per_day: 'Average /Day',
    total_saving_asset: 'Total Savings (Asset)',
    credit_label: 'Credit',
    debt_label: 'Debt',
    receivable_label: 'Receivable',
    funding_source: 'Funding Source',
    no_accounts: 'No accounts yet',
    cashflow_trend: 'Cashflow & 6-Month Trend',
    cashflow_summary: 'Cashflow Summary',
    no_income: 'No income yet',
    no_expense: 'No expense yet',
    financial_allocation: 'Financial Allocation',
    financial_allocation_sub: 'Distribution of income and expenses',
    dashboard_tx_history: 'Transaction History',
    dashboard_tx_history_sub: 'Last 10 transactions',
    no_transactions: 'No transactions yet',
    record_income: 'Record income',
    record_expense: 'Record expense',
    my_assets: 'My Assets',
    tx_all: 'All',
    my_assets_sub: 'View your asset list and values',
    total_assets: 'Total Assets',
    asset_price_buy: 'Buy Price',
    asset_price_now: 'Current Price',
    add_asset: 'Add Asset',
    edit_asset: 'Edit Asset',
    delete_asset: 'Delete Asset',
    period_weekly: 'Weekly',
    period_monthly: 'Monthly',
    period_yearly: 'Yearly',
    period_custom: 'Custom',
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot password?',
    reset_password_sent: 'Password reset email sent. Check your inbox!',
    login_with_google: 'Continue with Google',
    select_account_name: '— Select account name —',
    other_account_name: 'Account name...',
    start_journey: 'Start Your Financial Journey',
    onboard_tips: 'SteFin will strictly record your total current balance, then automatically calculate your financial trajectory moving forward.',
    toast_name_empty: 'Name cannot be empty',
    toast_profile_saved: 'Profile successfully updated.',
    toast_profile_failed: 'Failed to save profile.',
    toast_email_not_found: 'Could not find email.',
    toast_reset_sent: 'Password reset email sent successfully.',
    toast_reset_failed: 'Failed to send password reset email.',
    toast_cat_exist: 'Category already exists.',
    toast_cat_added: 'Custom category added.',
    toast_cat_failed_save: 'Failed to save category.',
    toast_cat_deleted: 'Category deleted.',
    toast_cat_failed_delete: 'Failed to delete category.',
    toast_pin_6_digit: 'PIN must be 6 digits.',
    toast_pin_mismatch: 'PIN confirmation does not match.',
    toast_pin_enabled: 'PIN successfully activated.',
    toast_pin_disabled: 'PIN disabled.',
    toast_pin_failed: 'Failed to save PIN.',
    toast_onboarding_done: 'Onboarding completed. Welcome to SteFin! 🎉',
    toast_tx_added: 'Transaction added successfully.',
    toast_tx_updated: 'Transaction updated.',
    toast_tx_deleted: 'Transaction deleted.',
    toast_acc_added: 'Funding account added.',
    toast_acc_updated: 'Account updated.',
    toast_acc_deleted: 'Account deleted.',
    toast_report_prep: 'Preparing report...',
    toast_report_sent: 'Report has been sent to your email! 📧',
    toast_report_failed: 'Failed to send report. Ensure a secure connection.',
    toast_receivable_paid: 'Receivable marked as paid.',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('stefin_lang');
      if (saved === 'id' || saved === 'en') return saved;
    }
    return 'id';
  });

  useEffect(() => {
    const saved = localStorage.getItem('stefin_lang');
    if (saved && (saved === 'id' || saved === 'en') && saved !== lang) {
      setLang(saved);
    }
  }, [lang]);

  const [privacyMode, setPrivacyMode] = useState(() => {
    return localStorage.getItem('stefin_privacy') === 'true';
  });

  const togglePrivacyMode = () => {
    setPrivacyMode(prev => {
      const next = !prev;
      localStorage.setItem('stefin_privacy', next);
      return next;
    });
  };

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('stefin_lang', newLang);
  };

  const t = (key, params) => {
    const getNested = (obj, path) => path.split('.').reduce((o, i) => (o ? o[i] : undefined), obj);
    
    // 1. Current lang, 2. Default lang (id), 3. Human readable fallback
    let text = getNested(translations[lang], key) || getNested(translations['id'], key);
    
    if (!text) {
      // Auto formatting fallback for missing keys during development
      text = key.split('.').pop().split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    }

    if (params) {
      Object.keys(params).forEach(k => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), params[k]);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, privacyMode, togglePrivacyMode }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
