import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  id: {
    dashboard: 'Dashboard',
    history: 'Riwayat Transaksi',
    assets: 'Aset & Utang',
    accounts: 'Akun Sumber Dana',
    profile: 'Profil',
    settings: 'Pengaturan',
    lang_pref: 'Preferensi Bahasa',
    lang_id: 'Bahasa Indonesia',
    lang_en: 'English',
    firebase_conn: 'Koneksi Firebase',
    offline_mode: 'Mode Offline',
    sign_out: 'Keluar',
    add_tx: 'Tambah Transaksi',
    app_desc: 'Your Financial Integrity, Simplified.',
    settings_desc: 'Atur preferensi aplikasi dan konfigurasi Firebase.',
    main_menu: 'Menu Utama',
    recent_tx: 'Transaksi Terakhir bulan ini',
    no_recent_tx: 'Belum ada transaksi.',
    tx_count: 'Transaksi',
    tx_all: 'Semua',
    tx_income: 'Pemasukan',
    tx_expense: 'Pengeluaran',
    tx_transfer: 'Transfer',
    tx_asset: 'Aset',
    tx_debt: 'Utang',
    no_tx_period: 'Belum ada transaksi di periode ini.',
    date: 'Tanggal',
    category: 'Kategori',
    desc: 'Keterangan',
    account: 'Akun',
    amount: 'Nominal',
    action: 'Aksi',
    debt_settlement: 'Pelunasan Utang',
    asset_settlement: 'Pelunasan Piutang',
    receivables: 'Piutang',
    registered_accounts: 'Akun Terdaftar',
    add_account: 'Tambah Akun',
    real_balance: 'Saldo Riil Saat Ini',
    adjust: 'Sesuaikan',
    delete: 'Hapus',
    cancel: 'Batal',
    save: 'Simpan',
    edit: 'Edit',
    total_income: 'Total Pendapatan',
    total_expense: 'Total Pengeluaran',
    net_worth: 'Total Kekayaan Bersih',
    stats: 'Statistik',
    total_tx: 'Total Transaksi',
    account_count: 'Jumlah Akun',
    active_months: 'Bulan Aktif',
    smart_input: 'Form input cerdas dengan tipe multi-transaksi',
    type: 'Jenis',
    source: 'Sumber',
    asset_src: 'Sumber Aset',
    debt_src: 'Sumber Utang',
    receivable_src: 'Sumber Piutang',
    exist_receivable: 'Piutang Sudah Ada Sebelumnya',
    exist_debt: 'Utang Sudah Ada Sebelumnya',
    exist_asset: 'Aset Sudah Dimiliki Sebelumnya',
    exist_receivable_desc: 'Pinjaman ini diberikan sebelum menggunakan SteFin.',
    exist_debt_desc: 'Utang ini sudah ada sebelum menggunakan SteFin.',
    exist_asset_desc: 'Aset ini sudah ada sebelum menggunakan SteFin.',
    balance_unchanged: 'Saldo akun tidak berubah.',
    new_receivable: 'Piutang Diberikan dari Dana Akun',
    new_debt: 'Pinjaman Baru (Dana Masuk ke Akun)',
    new_asset: 'Aset Dibeli dengan Dana Akun',
    new_receivable_desc: 'Pinjaman ini diberikan menggunakan saldo yang tercatat. Saldo akun berkurang sebesar nominal.',
    new_debt_desc: 'Dana pinjaman diterima ke akun. Saldo akun bertambah sebesar nominal.',
    new_asset_desc: 'Aset ini dibeli menggunakan saldo yang tercatat. Saldo akun berkurang sebesar nominal.',
    level_type: 'Tipe',
    sub_category: 'Sub-Kategori',
    src_account: 'Akun Sumber',
    target_account: 'Akun Tujuan',
    select_target: 'Pilih Akun Tujuan...',
    amount_rp: 'Nominal (Rp)',
    optional_note: 'Keterangan (opsional)',
    add: 'Tambah',
    tx_edit_title: 'Edit Transaksi',
    tx_add_title: 'Tambah Transaksi',
    acc_edit_title: 'Edit Akun',
    acc_add_title: 'Tambah Akun',
    acc_name: 'Nama Akun',
    init_balance: 'Saldo Awal',
    save_acc: 'Simpan Akun',
    add_acc: 'Tambah Akun',
    edit_acc: 'Edit Akun',
    adjust_balance: 'Sesuaikan Saldo',
    adjust_desc: 'Fungsi ini akan membuat transaksi "penyesuaian" agar saldo riil di sistem sesuai dengan kenyataan.',
    actual_balance: 'Saldo Aktual di Dunia Nyata',
    diff: 'Selisih',
    adjust_btn: 'Sesuaikan Sekarang',
    account_not_changed: 'Saldo {name} tetap tidak berubah.',
    account_increased: 'Saldo {name} bertambah {amount}.',
    account_decreased: 'Saldo {name} berkurang {amount}.',
    acc_name_placeholder: 'Nama Akun (e.g. BCA, Dana)',
    acc_type_bank: 'Bank',
    acc_type_cash: 'Kas',
    acc_type_ewallet: 'E-Wallet',
    sync_desc: 'Akan disinkronkan ke Firestore',
    onboard_welcome: 'Selamat Datang di SteFin',
    onboard_welcome_desc: 'Aplikasi pencatatan keuangan pintar tanpa form ribet. Mari siapkan akun pertamamu.',
    onboard_first_acc: 'Akun Pertamamu',
    onboard_smart_form: 'Coba Form Cerdas',
    onboard_start: 'Mulai SteFin',
    add_first_acc: 'Tambah Akun Pertama',
    step_of: 'Langkah {step} dari {total}',
    basic_profile: 'Profil Dasar',
    fullname: 'Nama Lengkap',
    continue_btn: 'Lanjutkan →',
    register_accs: 'Daftarkan Akun & Saldo Awal',
    register_accs_desc: 'Semua perubahan saldo akan dihitung otomatis dari titik ini.',
    back_btn: '← Kembali',
    start_btn: 'Mulai SteFin 🚀',
    main_features: 'Fitur Utama',
    f1_desc: 'Pantau pemasukan & pengeluaran bulanan secara visual real-time.',
    f2_desc: 'Saldo nyata yang berjalan dari bulan ke bulan, bukan per-periode.',
    f3_desc: 'Peringatan cerdas jika pola keuangan menurun.',
    f4_desc: 'Data tersimpan di cloud — aman, cepat, dan bisa diakses dari mana saja.',
    welcome_name: 'Halo',
    login: 'Masuk',
    register: 'Daftar',
    min_password: 'Password (min. 6 karakter)',
    create_account: 'Buat Akun',
    or: 'atau',
    operational_report: 'Laporan Operasional',
    savings: 'Tabungan',
    from_income: 'dari pemasukan',
    cashflow: 'Arus Kas',
    cashflow_desc: 'Semua transaksi yang mengubah saldo akun bulan ini',
    debit: 'Debit (Masuk)',
    credit: 'Kredit (Keluar)',
    debt_in_req: 'Pinjaman Diterima',
    asset_bought: 'Pembelian Aset',
    receivable_given: 'Piutang Diberikan',
    total_debit: 'Total Debit',
    total_credit: 'Total Kredit',
    balance_change: 'Perubahan Saldo Akun',
    debit_minus_credit: 'Debit − Kredit',
    cashflow_6m: 'Arus Kas 6 Bulan',
    live_sync: 'Sinkronisasi Langsung',
    registered_accounts: 'Akun Terdaftar',
    cash_balance: 'Saldo kas',
    real_balance: 'Saldo Aktual',
    adjust: 'Sesuaikan',
    delete: 'Hapus',
    loading_stefin: 'Memuat SteFin...',
    loading_data: 'Memuat data keuangan...',
  },
  en: {
    dashboard: 'Dashboard',
    history: 'Transaction History',
    assets: 'Assets & Debts',
    accounts: 'Funding Accounts',
    profile: 'Profile',
    settings: 'Settings',
    lang_pref: 'Language Preference',
    lang_id: 'Bahasa Indonesia',
    lang_en: 'English',
    firebase_conn: 'Firebase Connection',
    offline_mode: 'Offline Mode',
    sign_out: 'Sign Out',
    add_tx: 'Add Transaction',
    app_desc: 'Your Financial Integrity, Simplified.',
    settings_desc: 'Manage application preferences and Firebase configuration.',
    main_menu: 'Main Menu',
    recent_tx: 'Recent Transactions this month',
    no_recent_tx: 'No recent transactions.',
    tx_count: 'Transactions',
    tx_all: 'All',
    tx_income: 'Income',
    tx_expense: 'Expense',
    tx_transfer: 'Transfer',
    tx_asset: 'Asset',
    tx_debt: 'Debt',
    no_tx_period: 'No transactions in this period.',
    date: 'Date',
    category: 'Category',
    desc: 'Description',
    account: 'Account',
    amount: 'Amount',
    action: 'Action',
    debt_settlement: 'Debt Settlement',
    asset_settlement: 'Receivable Settlement',
    receivables: 'Receivables',
    registered_accounts: 'Registered Accounts',
    add_account: 'Add Account',
    real_balance: 'Current Real Balance',
    adjust: 'Adjust',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    total_income: 'Total Income',
    total_expense: 'Total Expense',
    net_worth: 'Total Net Worth',
    stats: 'Statistics',
    total_tx: 'Total Transactions',
    account_count: 'Account Count',
    active_months: 'Active Months',
    smart_input: 'Smart input form with multi-transaction types',
    type: 'Type',
    source: 'Source',
    asset_src: 'Asset Source',
    debt_src: 'Debt Source',
    receivable_src: 'Receivable Source',
    exist_receivable: 'Pre-existing Receivable',
    exist_debt: 'Pre-existing Debt',
    exist_asset: 'Pre-existing Asset',
    exist_receivable_desc: 'This loan was given before using SteFin.',
    exist_debt_desc: 'This debt existed before using SteFin.',
    exist_asset_desc: 'This asset was owned before using SteFin.',
    balance_unchanged: 'Account balance remains unchanged.',
    new_receivable: 'Receivable from Account Funds',
    new_debt: 'New Debt (Funds received into Account)',
    new_asset: 'Asset Bought with Account Funds',
    new_receivable_desc: 'This loan decreases the account balance by the nominal amount.',
    new_debt_desc: 'This debt increases the account balance by the nominal amount.',
    new_asset_desc: 'This asset decreases the account balance by the nominal amount.',
    level_type: 'Level Type',
    sub_category: 'Sub-Category',
    src_account: 'Source Account',
    target_account: 'Target Account',
    select_target: 'Select Target Account...',
    amount_rp: 'Amount (Rp)',
    optional_note: 'Note (optional)',
    add: 'Add',
    tx_edit_title: 'Edit Transaction',
    tx_add_title: 'Add Transaction',
    acc_edit_title: 'Edit Account',
    acc_add_title: 'Add Account',
    acc_name: 'Account Name',
    init_balance: 'Initial Balance',
    save_acc: 'Save Account',
    add_acc: 'Add Account',
    edit_acc: 'Edit Account',
    adjust_balance: 'Adjust Balance',
    adjust_desc: 'This function creates an "adjustment" transaction so the system balance matches reality.',
    actual_balance: 'Actual Real-World Balance',
    diff: 'Difference',
    adjust_btn: 'Adjust Now',
    account_not_changed: 'Account {name} balance remains unchanged.',
    account_increased: 'Account {name} balance increased by {amount}.',
    account_decreased: 'Account {name} balance decreased by {amount}.',
    acc_name_placeholder: 'Account Name (e.g. Bank, Cash)',
    acc_type_bank: 'Bank',
    acc_type_cash: 'Cash',
    acc_type_ewallet: 'E-Wallet',
    sync_desc: 'Will be synchronized to Firestore',
    onboard_welcome: 'Welcome to SteFin',
    onboard_welcome_desc: 'Smart financial tracking without complex forms. Let\'s set up your first account.',
    onboard_first_acc: 'Your First Account',
    onboard_smart_form: 'Try Smart Form',
    onboard_start: 'Start SteFin',
    add_first_acc: 'Add First Account',
    step_of: 'Step {step} of {total}',
    basic_profile: 'Basic Profile',
    fullname: 'Full Name',
    continue_btn: 'Continue →',
    register_accs: 'Register Accounts & Initial Balance',
    register_accs_desc: 'All balance changes will be automatically calculated from this point forward.',
    back_btn: '← Back',
    start_btn: 'Start SteFin 🚀',
    main_features: 'Key Features',
    f1_desc: 'Monitor monthly income & expenses visually in real-time.',
    f2_desc: 'Real running balance month-to-month, not just isolated periods.',
    f3_desc: 'Smart warnings if financial patterns decline over 3 months.',
    f4_desc: 'Data stored securely in the cloud — fast and accessible anywhere.',
    welcome_name: 'Hello',
    login: 'Login',
    register: 'Register',
    min_password: 'Password (min. 6 characters)',
    create_account: 'Create Account',
    or: 'or',
    operational_report: 'Operational Report',
    savings: 'Savings',
    from_income: 'from income',
    cashflow: 'Cash Flow',
    cashflow_desc: 'All transactions modifying account balance this month',
    debit: 'Debit (In)',
    credit: 'Credit (Out)',
    debt_in_req: 'Debt Received',
    asset_bought: 'Asset Purchased',
    receivable_given: 'Receivable Given',
    total_debit: 'Total Debit',
    total_credit: 'Total Credit',
    balance_change: 'Balance Change',
    debit_minus_credit: 'Debit − Credit',
    cashflow_6m: '6 Months Cash Flow',
    live_sync: 'Live Sync',
    registered_accounts: 'Registered Accounts',
    cash_balance: 'Cash balance',
    real_balance: 'Actual Balance',
    adjust: 'Adjust',
    delete: 'Delete',
    loading_stefin: 'Loading SteFin...',
    loading_data: 'Loading financial data...',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('id');

  useEffect(() => {
    const saved = localStorage.getItem('stefin_lang');
    if (saved && (saved === 'id' || saved === 'en')) {
      setLang(saved);
    }
  }, []);

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('stefin_lang', newLang);
  };

  const t = (key, params) => {
    let text = translations[lang]?.[key] || key;
    if (params) {
      Object.keys(params).forEach(k => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), params[k]);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
